donationsite/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, IntegerField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from donationsite.models import User


class RegistrationForm(FlaskForm):
    name = StringField('Name', validators=[
                       DataRequired(), Length(min=2, max=30)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):

        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email already taken')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Login')


class AddCVForm(FlaskForm):
    cv_file = FileField('Add CV', validators=[
                        FileAllowed(['doc', 'docx', 'pdf'])])
    submit = SubmitField('Upload')


class AddImageForm(FlaskForm):
    image_file = FileField('Update Profile Picture', validators=[
                           FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Upload')


class AddAboutForm(FlaskForm):
    self_desc = StringField('About', validators=[
                            DataRequired()])
    submit = SubmitField('Save')


class AddDegreeForm(FlaskForm):
    title = StringField('Degree Title', validators=[
                        DataRequired(), Length(min=5, max=120)])
    institution = StringField('Institution', validators=[
                              DataRequired(), Length(min=5, max=120)])
    grad_year = StringField('Graduation Year', validators=[
                            DataRequired(), Length(min=4, max=4)])
    submit = SubmitField('Save')


class BankDetailForm(FlaskForm):
    account_holder = StringField('Account Holder', validators=[
                                 DataRequired(), Length(min=2, max=30)])
    account_number = IntegerField('Account Number', validators=[
        DataRequired()])
    sortcode = IntegerField('Sort Code', validators=[
        DataRequired()])
    submit = SubmitField('Save')


class ViewCVForm(FlaskForm):
    graduate = IntegerField('graduate', validators=[DataRequired()])
    submit = SubmitField('View CV')


class RequestResetForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):

        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('No account with that email')


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[
                                     DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

donationsite/accounts/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect, jsonify, send_from_directory, current_app
import os
from donationsite import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from donationsite.models import User, Degree, UserDegree, Bankdetails, UserBankdetails
from donationsite.accounts.forms import (RegistrationForm, LoginForm, AddCVForm, AddImageForm,
                                         AddAboutForm, AddDegreeForm, BankDetailForm, ViewCVForm,
                                         RequestResetForm, ResetPasswordForm)
from donationsite.accounts.utils import save_cv, save_image, send_reset_email


accounts = Blueprint('accounts', __name__)


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('accounts.account'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('accounts.account'))

        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template("login.html", title='Login', form=form)


@accounts.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('accounts.account'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(name=form.name.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(
            f'Account created for {form.name.data}, please log in', 'success')
        return redirect(url_for('accounts.login'))
    return render_template("register.html", title='Register', form=form)


@accounts.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('accounts.login'))


@accounts.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    cvform = AddCVForm()
    imageform = AddImageForm()
    aboutform = AddAboutForm()
    degreeform = AddDegreeForm()
    viewcvform = ViewCVForm()

    if cvform.validate_on_submit():
        if not current_user.cv_file:
            if cvform.cv_file.data:
                cv = save_cv(cvform.cv_file.data)
                current_user.cv_file = cv
                db.session.commit()
                flash('Your CV has been uploaded', 'success')
        elif current_user.cv_file:
            if cvform.cv_file.data:
                cvfilename = current_user.cv_file
                path = os.path.join(
                    current_app.root_path, 'static/cvfiles', cvfilename)
                os.remove(path)
                cv = save_cv(cvform.cv_file.data)
                current_user.cv_file = cv
                db.session.commit()
                flash('Your CV has been updated', 'success')

    if imageform.validate_on_submit():
        if imageform.image_file.data:
            pp = save_image(imageform.image_file.data)
            current_user.image_file = pp
            db.session.commit()
            flash('Your profile photo has been updated', 'success')

    if aboutform.validate_on_submit():
        current_user.self_desc = aboutform.self_desc.data
        db.session.commit()
        flash('Profile updated', 'success')
    elif request.method == 'GET':
        if current_user.self_desc:
            aboutform.self_desc.data = current_user.self_desc

    if degreeform.validate_on_submit():
        degree = Degree(title=degreeform.title.data,
                        institution=degreeform.institution.data, grad_year=degreeform.grad_year.data)
        db.session.add(degree)
        db.session.commit()
        userdegree = Degree.query.filter_by(
            title=degreeform.title.data, institution=degreeform.institution.data, grad_year=degreeform.grad_year.data).first()
        current_user.degree = []
        current_user.degree.append(userdegree)
        db.session.commit()
        flash('Your degree has been updated', 'success')
    elif request.method == 'GET':
        if current_user.degree != []:
            usrdegree = current_user.degree[0]
            degreeform.title.data = usrdegree.title
            degreeform.institution.data = usrdegree.institution
            degreeform.grad_year.data = usrdegree.grad_year

    if viewcvform.validate_on_submit():
        cvgradid = viewcvform.graduate.data
        cvgrad = User.query.filter_by(id=cvgradid).first()
        cvfile = cvgrad.cv_file
        cvfiles = os.path.join(current_app.root_path, 'static/cvfiles')
        return send_from_directory(directory=cvfiles, filename=cvfile)

    image_file = url_for(
        'static', filename='profilepics/' + current_user.image_file)

    return render_template("account.html", aboutform=aboutform, cvform=cvform, imageform=imageform,
                           degreeform=degreeform, image_file=image_file, viewcvform=viewcvform)


@accounts.route('/bankdetails', methods=['GET', 'POST'])
def bankdetails():
    form = BankDetailForm()

    if form.validate_on_submit():
        accountNumber = str(form.account_number.data)
        sortCode = str(form.sortcode.data)
        bank = Bankdetails(account_holder=form.account_holder.data,
                           account_number=accountNumber,
                           sort_code=sortCode)
        db.session.add(bank)
        db.session.commit()
        usrbank = Bankdetails.query.filter_by(
            account_number=accountNumber).first()
        current_user.bank_details = []
        current_user.bank_details.append(usrbank)
        db.session.commit()
        flash('Your bank details have been updated', 'success')
        return redirect(url_for('accounts.account'))

    elif request.method == 'GET':
        if current_user.bank_details != []:
            userbank = current_user.bank_details[0]
            form.account_holder.data = userbank.account_holder
            form.account_number.data = userbank.account_number
            form.sortcode.data = userbank.sort_code

    return render_template('bankdetails.html', form=form)


@accounts.route('/forgotpass', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('accounts.account'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Email has been sent to reset your password', 'success')
        return redirect(url_for('accounts.login'))


    return render_template('forgotpass.html', form=form)


@accounts.route('/resetpassword/<token>', methods=['POST', 'GET'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('accounts.account'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or Expired link', 'warning')
        return redirect(url_for('accounts.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(
            f'Password has been updated, please log in', 'success')
        return redirect(url_for('accounts.login'))
    return render_template('resetpass.html', form=form)

donationsite/donations/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect, jsonify
from donationsite import stripe_keys
from donationsite.models import User, Bankdetails, UserBankdetails
import stripe
from donationsite.donations.utils import donateinfo_email


donations = Blueprint('donations', __name__)


@donations.route('/makedonation')
def makedonation():

    q = request.args.get('q', type=str)
    if q:
        print(q)
        grads = User.query.filter(User.name.contains(q)).all()
    else:
        grads = User.query.all()

    return render_template("makedonation.html", grads=grads)


stripe.api_key = stripe_keys['secret_key']


@donations.route('/create-checkout-session/<donatedTo>', methods=['POST'])
def create_checkout_session(donatedTo):
    session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[{
            'price_data': {
                    'currency': 'gbp',
                    'product_data': {
                                'name': '£5 Donation',
                                'description': donatedTo
                    },
                    'unit_amount': 500,
                    },
            'quantity': 1,
        }],
        mode='payment',
        success_url='http://localhost:5000/success',
        cancel_url='http://localhost:5000/cancel',
    )

    return jsonify(id=session.id)


@donations.route('/success', methods=['POST', 'GET'])
def thanks():
    return render_template("thanks.html")


@donations.route('/cancel')
def cancel():
    return render_template("cancel.html")

donationsite/main/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect, jsonify, send_from_directory, current_app
import os
from donationsite.models import User
from donationsite.main.forms import ViewCVForm

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():

    grads = User.query.all()

    return render_template("index.html", grads=grads)


@main.route('/profile/<gradid>', methods=['GET', 'POST'])
def profile(gradid):
    grad = User.query.filter_by(id=gradid).first()
    image_file = url_for(
        'static', filename='profilepics/' + grad.image_file)

    viewcvform = ViewCVForm()
    if viewcvform.validate_on_submit():
        cvgradid = viewcvform.graduate.data
        cvgrad = User.query.filter_by(id=cvgradid).first()
        cvfile = cvgrad.cv_file
        cvfiles = os.path.join(current_app.root_path, 'static/cvfiles')
        return send_from_directory(directory=cvfiles, filename=cvfile)

    return render_template('profile.html', grad=grad, image_file=image_file, viewcvform=viewcvform)

donationsite/templates/account.html
{% extends 'base.html' %}

{% block head %}

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/account.css') }}">

	<!-- Fancybox -->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/jquery.fancybox.min.css') }}">

{% endblock %}

{% block content %}

	<div class="bg-primary py-5 mb-5">
		<div class="container h-100">
			<div class="row h-100 align-items-center">
				<div class="col-lg-12">
					<h2 class="display-4 text-white mt-5 mb-2">My Account</h2>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
						{% for category, message in messages %}
							<div class="alert alert-{{ category }}">
								{{ message }}
							</div>
						{% endfor %}
					{% endif %}
				{% endwith %}
			</div>
		</div>
		<!-- Intro Info -->
		<div class="row">
			<div class="col-md-8 mb-5">
				<h2>{{ current_user.name }}</h2>
				<hr>
				<div class="row">
					<div class="col-md-4 imagediv">
						<a data-fancybox data-src='#addImage' href=""><img src="{{ image_file }}"></a>
					</div>
					<div class="col-md-8">
						<p>{{ current_user.self_desc }}</p>
						<div class="row">
							<div class="col-md-6">
								{% if not current_user.cv_file %}
									<small><a data-fancybox data-src='#addCV' href="">Add CV</a></small>
								{% elif current_user.cv_file %}
									<form method="POST" action="">
										{{ viewcvform.csrf_token }}
										{{ viewcvform.graduate(style="display:none;", value=current_user.id) }}
										<small>{{ viewcvform.submit(class="looklikelink") }}</small>
										<br>
										<small><a data-fancybox data-src='#addCV' href="">Update CV</a></small>
									</form>
								{% endif %}
							</div>
							<div class="col-md-6 text-right">
								<small><a data-fancybox data-src='#addDesc' href="">Edit</a></small>
							</div>
						</div>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-md-12 card">
						<div class="card-body">
							{% if not current_user.bank_details %}
								<h3 class="card-title">Your Bank Details</h3>
								<p class="card-text">Your account number and sortcode</p>
							{% elif current_user.bank_details %}
								<h3 class="card-title">Bank Details</h3><br>
								<p class="card-text">Account Holder : {{ current_user.bank_details[0].account_holder }}</p><br>
								<p class="card-text">Account Number : {{ current_user.bank_details[0].account_number }}</p><br>
								<p class="card-text">Sort Code : {{ current_user.bank_details[0].sort_code }}</p>
							{% endif %}
							<small><a href="{{ url_for('accounts.bankdetails') }}">Edit</a></small>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 mb-5">
				<h3>My Details</h3>
				<hr>
				<div class="row">
					<div class="col-md-12">
						<div class="card degree">
							<div class="card-body">
								{% if not current_user.degree %}
									<h4 class="card-title">Your Degree Title</h4>
									<p class="card-text">Institution<br>Graduated year</p>
								{% elif current_user.degree %}
									<h4 class="card-title">{{ current_user.degree[0].title }}</h4>
									<p class="card-text">{{ current_user.degree[0].institution }}<br><small><i>graduated in {{ current_user.degree[0].grad_year }}</i></small></p>
								{% endif %}
								<small><a data-fancybox data-src='#addDegree' href="">Edit</a></small>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Fancybox -->
	<div style="display: none;" id="addCV">
	    <div class="container">
	        <div class="row">
	            <div class="col-md-12">
	            	<h4>Upload CV file</h4>
	            	<form method="POST" action="" enctype="multipart/form-data">
	            		<div>
	            			<div class="form-group">
	            				{{ cvform.csrf_token }}
	            				{{ cvform.cv_file(class="form-control-file") }}
	            				{% if cvform.cv_file.errors %}
	            					{% for error in cvform.cv_file.errors %}
	            						<span class="text-danger">{{ error }}</span></br>
	            					{% endfor %}
	            				{% endif %}
	            			</div>
	            			<hr>
	            			{{ cvform.submit(class="btn btn-lg btn-primary btn-block text-uppercase") }}
	            		</div>
	            	</form>
	            </div>
	        </div>
	    </div>
	</div>
	<div style="display: none;" id="addImage">
	    <div class="container">
	        <div class="row">
	            <div class="col-md-12">
	            	<h4>Upload Profile Photo</h4>
	            	<form method="POST" action="" enctype="multipart/form-data">
	            		<div>
	            			<div class="form-group">
	            				{{ imageform.csrf_token }}
	            				{{ imageform.image_file(class="form-control-file") }}
	            				{% if imageform.image_file.errors %}
	            					{% for error in imageform.image_file.errors %}
	            						<span class="text-danger">{{ error }}</span></br>
	            					{% endfor %}
	            				{% endif %}
	            			</div>
	            			<hr>
	            			{{ imageform.submit(class="btn btn-lg btn-primary btn-block text-uppercase") }}
	            		</div>
	            	</form>
	            </div>
	        </div>
	    </div>
	</div>
	<div style="display: none;" id="addDesc">
	    <div class="container">
	        <div class="row">
	            <div class="col-md-12">
	                <h4>About Me</h4>
	                <form id="aboutform" method="POST" action="">
						<div class="form-group">
							{{ aboutform.csrf_token }}

							{% if aboutform.self_desc.errors %}
								{{ aboutform.self_desc(class="form-control form-control-lg is-invalid") }}
								<div class="invalid-feedback">
									{% for error in aboutform.self_desc.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ aboutform.self_desc(class="form-control form-control-lg") }}
							{% endif %}
						</div>
						<hr>
						{{ aboutform.submit(id="submitbutton", class="btn btn-lg btn-primary btn-block text-uppercase") }}
	                </form>
	            </div>
	        </div>
	    </div>
	</div>

	<div style="display: none;" id="addDegree">
	    <div class="container">
	        <div class="row">
	            <div class="col-md-12">
	                <h4>My Degree</h4>
	                <form id="aboutform" method="POST" action="">
	                	{{ degreeform.csrf_token }}
						<div class="form-group">
							
							{{ degreeform.title.label(class="form-control-label") }}

							{% if degreeform.title.errors %}
								{{ degreeform.title(class="form-control form-control-lg is-invalid") }}
								<div class="invalid-feedback">
									{% for error in degreeform.title.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ degreeform.title(class="form-control form-control-lg") }}
							{% endif %}
						</div>
						<div class="form-group">
							{{ degreeform.institution.label(class="form-control-label") }}

							{% if degreeform.institution.errors %}
								{{ degreeform.institution(class="form-control form-control-lg is-invalid") }}
								<div class="invalid-feedback">
									{% for error in degreeform.institution.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ degreeform.institution(class="form-control form-control-lg") }}
							{% endif %}
						</div>
						<div class="form-group">
							{{ degreeform.grad_year.label(class="form-control-label") }}

							{% if degreeform.grad_year.errors %}
								{{ degreeform.grad_year(class="form-control form-control-lg is-invalid") }}
								<div class="invalid-feedback">
									{% for error in degreeform.grad_year.errors %}
										<span>{{ error }}</span>
									{% endfor %}
								</div>
							{% else %}
								{{ degreeform.grad_year(class="form-control form-control-lg") }}
							{% endif %}
						</div>
						<hr>
						{{ degreeform.submit(id="submitbutton", class="btn btn-lg btn-primary btn-block text-uppercase") }}
	                </form>
	            </div>
	        </div>
	    </div>
	</div>
	



{% endblock content %}

{% block js %}

	<script type="text/javascript" src="{{ url_for('static', filename='javascript/account.js') }}"></script>

	<!-- Fancybox -->
	<script type="text/javascript" src="{{ url_for('static', filename='javascript/jquery.fancybox.min.js') }}"></script>

{% endblock %}

donationsite/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Donation website to donate to recent graduates amidst the covid-19 pandemic">
	<meta name="keywords" content="Donate, Donation, Donate to graduates, Graduates, Recent graduates, donation website">
	<meta name="developer" content="Kunhee Ha">

	<!-- Favicon -->
	<link rel="shortcut icon" href="{{ url_for('static', filename='icons/favicon.ico') }}">
	<!-- Font Awesome -->
    <link rel="stylesheet" href="{{ url_for('static', filename='icons/font-awesome-4.7.0/css/font-awesome.min.css') }}">

	<title>Donate to Grads</title>

	<!-- Bootstrap -->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">

	{# Main CSS #}
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">


	{% block head %}{% endblock %}
</head>
<body>
	<header>
		<!-- Navbar -->
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
			<div class="container">
				<a class="navbar-brand" href="/">Donate2Grads</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('donations.makedonation') }}">Make a Donation</a>
						</li>
						{% if current_user.is_authenticated %}
						<li class="nav-item">
								<a class="nav-link" href="{{ url_for('accounts.account') }}">Account</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('accounts.logout') }}">Logout</a>
							</li>
						{% else %}
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('accounts.register') }}">Register</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{{ url_for('accounts.login') }}">Login</a>
							</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<main class="flex-fill">
		{% block content %}{% endblock %}
	</main>



	<!-- Footer -->
	<footer class="footer mt-auto py-3">
		<div class="container">
			<span><a class="footer-link" href="https://www.linkedin.com/in/kunheeha" target="_blank">Developer - Kunhee Ha</a></span>
		</div>
	</footer>



	<!-- jQuery -->
	<script type="text/javascript" src="{{ url_for('static', filename='javascript/jquery/jquery.min.js') }}"></script>

	<!-- Bootstrap -->
	<script type="text/javascript" src="{{ url_for('static', filename='bootstrap/js/bootstrap.bundle.min.js') }}"></script>
	{% block js %}{% endblock %}
</body>

donationsite/templates/cancel.html
{% extends 'base.html' %}
{% block head %}{% endblock %}

{% block content %}

	<!-- Header -->
	<div class="bg-primary py-5 mb-5">
		<div class="container h-100">
			<div class="row h-100 align-items-center">
				<div class="col-lg-12">
					<h1 class="display-4 text-white mt-5 mb-2">Payment Cancelled</h1>
				</div>
			</div>
		</div>
	</div>

	<!-- MAIN -->
	<div class="container">
		<!-- Intro Info -->
		<div class="row">
			<div class="col-md-8 mb-5">
				<hr>
				<p><a href="{{ url_for('donations.makedonation') }}">Back to donations</a><br><a href="{{ url_for('main.index') }}">Back to homepage</a></p>
			</div>
			<div class="col-md-4 mb-5">
				<h2>Are you a Graduate?</h2>
				<hr>
				<p>Sign Up <a href="/register">now</a></p>
			</div>
		</div>
	</div>

{% endblock content %}

donationsite/templates/index.html
{% extends 'base.html' %}

{% block head %}

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/business-frontpage.css') }}">

{% endblock %}

{% block content %}
	<!-- Header -->
	<div class="bg-primary py-5 mb-5">
		<div class="container h-100">
			<div class="row h-100 align-items-center">
				<div class="col-lg-12">
					<h1 class="display-4 text-white mt-5 mb-2">Donate to Graduates</h1>
					<p class="lead mb-5 text-white-50">Spend your hard earned cash on lazy jobless graduates</p>
					<form class="form-inline my-2 my-lg-0 searchForm">
						<input class="form-control mr-sm-2 searchValue" type="search" placeholder="Search for Graduates" aria-label="Search">
						<button class="btn btn-light my-2 my-sm-0" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
					</form>
				</div>
			</div>
		</div>
	</div>

	<!-- MAIN -->
	<div class="container">
		<!-- Intro Info -->
		<div class="row">
			<div class="col-md-8 mb-5">
				<h2>Donating</h2>
				<hr>
				<p>*Insert deep and moving paragraph about the good that donations can do*<br>Spend your hard earned cash on helping lazy jobless graduates do what they do best - nothing. Fund their existence!</p>
				<a class="btn btn-primary btn-lg" href="{{ url_for('donations.makedonation') }}">Donate Now &raquo;</a>
			</div>
			<div class="col-md-4 mb-5">
				<h2>Are you a Graduate?</h2>
				<hr>
				<p>You can get money from randomers for being an absolute nobody with crippling debt and no future.<br>Sign up <a href="{{ url_for('accounts.register') }}">NOW</a></p>
			</div>
		</div>
		<!-- Profiles -->
		<div class="row">
			{% if grads|length > 0 %}
				{% for grad in grads %}
				<div class="col-md-4 mb-5">
					<div class="card h-100">
						{% if grad.image_file != 'default.jpg' %}
							<img class="card-img-top" src="{{ url_for('static', filename='profilepics/'+grad.image_file) }}" alt="">
						{% endif %}
						<div class="card-body">
							<h4 class="card-title">{{ grad.name }}</h4>
							<p class="card-text">{{ grad.self_desc }}</p>
						</div>
						<div class="card-footer">
							<button data-gradid="{{ grad.id }}" class="btn btn-primary donateButton">View</button>
						</div>
					</div>
				</div>
				{% endfor %}
			{% elif grads|length == 0 %}
				<div class="col-md-12">
					<h4>There were no graduates matching your search</h4>
				</div>
			{% endif %}
		</div>
	</div>
{% endblock content %}

{% block js %}

	<script type="text/javascript" src="{{ url_for('static', filename='javascript/index.js') }}"></script>

{% endblock %}